name: Build and Deploy Github Rank
on:
  push:
    # branches:
    #   - master
    tags:
      - v*
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/

    - run: npm ci
    - run: npm run get:o
      env: 
        ID: ${{ secrets.GITHUB_ID }}
        SECRET: ${{ secrets.GITHUB_SECRET }}
    - run: npm run get
      env: 
        ID: ${{ secrets.GITHUB_ID }}
        SECRET: ${{ secrets.GITHUB_SECRET }}
    - run: npm run start
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    - name: Build and Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./web